# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - plantcareAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Specify the correct working directory for your backend
      - name: Install Dependencies
        working-directory: ./backend  # Adjust this if your backend folder has a different path
        run: npm install

      - name: Build Backend
        working-directory: ./backend  # Adjust this if your backend folder has a different path
        run: npm run build --if-present

      # Package the backend into a zip file for deployment
      - name: Archive backend content
        run: zip -r backend.zip ./backend  # Package the backend folder into a zip file
        shell: bash

      # Upload the packaged backend (artifact)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend.zip  # Upload the zipped backend for deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'plantcareAPI'
          slot-name: 'Production'
          package: ./backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F956D6E696E54F1C83AA0D5433F6AE49 }}
